2023-12-01 14:22:21,137 [INFO]: Google Search Automation started.
2023-12-01 14:23:07,935 [INFO]: Google Search Automation completed successfully.
2023-12-01 14:23:07,937 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe88505660>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ba65fdd9dcc2f77cc1ed01e1122749ed
2023-12-01 14:23:07,939 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe885071f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ba65fdd9dcc2f77cc1ed01e1122749ed
2023-12-01 14:23:07,941 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe88505390>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/ba65fdd9dcc2f77cc1ed01e1122749ed
2023-12-01 14:44:19,754 [INFO]: Google Search Automation started.
2023-12-01 14:45:10,455 [INFO]: Google Search Automation started.
2023-12-01 14:45:48,544 [INFO]: Google Search Automation completed successfully.
2023-12-01 14:45:48,546 [WARNING]: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a13d66410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/540096d7e0a31416dc05a940532497a4
2023-12-01 14:45:48,548 [WARNING]: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a13d67160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/540096d7e0a31416dc05a940532497a4
2023-12-01 14:45:48,550 [WARNING]: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a13d665f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/540096d7e0a31416dc05a940532497a4
